DROP SCHEMA IF EXISTS eval CASCADE;
DROP SCHEMA IF EXISTS ops CASCADE;
DROP SCHEMA IF EXISTS iam CASCADE;
DROP SCHEMA IF EXISTS epi CASCADE;
DROP SCHEMA IF EXISTS kg CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;
