version: "2"
linters:
  enable:
    - modernize
    - govet
    - staticcheck
    - errcheck
    - revive
    - gocritic
    - sqlclosecheck
    - rowserrcheck
    - unconvert
    - misspell
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
